#  Copyright 2021 Collate
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Publish openmetadata-ingestion

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag being built"

jobs:
  publish-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Ubuntu related dependencies
        run: |
          sudo apt-get install -y libsasl2-dev unixodbc-dev python3-venv
      - name: Install and Publish Test PyPi packages
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME_TEST }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_TEST }}
        run: |
          make install_dev install
          cd ingestion; \
            python setup.py install sdist bdist_wheel; \
            twine check dist/*; \
            twine upload -r testpypi dist/*
  publish:
    needs: [publish-test]
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Ubuntu related dependencies
        run: |
          sudo apt-get install -y libsasl2-dev unixodbc-dev python3-venv
      - name: Install and Publish PyPi packages
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          make install_dev install
          cd ingestion; \
            python setup.py install sdist bdist_wheel; \
            twine check dist/*; \
            twine upload -r dist/*
